services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: pos
      POSTGRES_PASSWORD: "YrvPBXQ9uhEkhHSAuY_aZq-mkCW7x7pl"
    volumes:
      - pos_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "FYUXhdBcLwOrKPX--wxuYCFQNgSAE1_R"
    environment:
      - REDIS_REPLICATION_MODE=master

  pg-admin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  
  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: pos_test
      POSTGRES_PASSWORD: "DntKCEm3cVOo9s9M6zWod1rMeHVIEGb_"
    volumes:
      - pos_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "PCW6GGZXHVCqGAX-A3Vd605vzD6StSTy"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  pos_data:
  pos_test_data:
  pgadmin-data: