name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: "3.2.2"
      SERVERPOD_PASSWORD_database: "8HdVLiLaAboM2tuQdjp2j_bVURau_1gP"
      SERVERPOD_PASSWORD_redis: "7FW9nm9YWIdgetbCcaE-ugbYK-GKo1zH"

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"

      - name: Start containers
        working-directory: pos_server
        run: docker compose up --build -d

      - name: Install dependencies
        working-directory: pos_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: pos_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: pos_server
        run: serverpod generate

      - name: Run tests
        working-directory: pos_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: pos_server
        run: docker compose down -v
